### ISSUE TITLE
Problem with Python script

### ISSUE THREAD

**Issue by Jan-van-Waaij** [djsutherland/arxiv-collector#1]
Dear Dougal,

I get the following ValueError: Unexpected EOF. I'm using Windows 10 and I have 

file.tex
mystylefile.sty
file.bbl 

as files. Or does this script not work with Windows?

Best,

Jan

**Comment by djsutherland** [comment]
Hi @Jan-van-Waaij – sorry, I totally missed this issue (my github notifications are kind of a disaster).

It's pretty likely that something is going wrong on Windows; I don't use it and so haven't tested there. Can you post the full output of `latexmk -silent -pdf -deps file.tex` on your system? The script parses that, and maybe it looks a little different on Windows than on Linux/Mac.

**Comment by Jan-van-Waaij** [comment]
Dear Dougal,

Thank you for the effort. It seems not to work:

C:\Users\Admin\Documents\Programmeren\Latex\Test>latexmk -silent -pdf -deps file.tex
latexmk: The script engine could not be found.
latexmk: Data: scriptEngine="perl.exe", scriptName="latexmk"

Best,

Jan

**Comment by djsutherland** [comment]
Ah, well that's an issue with your tex installation (seems like maybe you don't have perl installed?). The script as is entirely depends on `latexmk` and can't do anything without it. I can't really help with debugging that since I know nothing about Windows, though.
