### ISSUE TITLE
Bad output of latexmk --version i.e. v4.69a

### ISSUE THREAD

**Issue by felixhekhorn** [djsutherland/arxiv-collector#12]
Thanks for all the good work (it is really useful!) but unfortunately your script is broken again (most likely latexmk faults)

```
Traceback (most recent call last):
  File "./arxiv_collector.py", line 378, in <module>
    main()
  File "./arxiv_collector.py", line 353, in main
    version = get_latexmk_version(args.latexmk)
  File "./arxiv_collector.py", line 77, in get_latexmk_version
    raise ValueError("Bad output of {} --version:\n{}".format(latexmk, out))
ValueError: Bad output of latexmk --version:

Latexmk, John Collins, 17 Apr. 2020. Version 4.69a
```
the problem is the "." after "Apr." 

I quick-fixed it by changing
`version_re = re.compile(r"Latexmk, John Collins, \d+ \w+\. \d+\. Version (.*)$")`

but maybe one should take a deeper look into `latexmk` to see what they do there (which I didn't manage in the hurry just now)

**Comment by djsutherland** [comment]
Hi @felixhekhorn – sorry for the delayed response. This should have been fixed by https://github.com/djsutherland/arxiv-collector/commit/377301b87dea4db06f06fcc7ca05ffb63082c528 (#11), in 0.3.5, and is working for me locally:

```
$ ./tmp-latexmk --version

Latexmk, John Collins, 17 Apr. 2020. Version 4.69a

$ arxiv-collector --latexmk ./tmp-latexmk counterexample
Building counterexample...
Build complete, gathering outputs...
Output in arxiv.tar.gz: 1 files, 2KiB compressed
```

Please re-open if it still fails for you with `arxiv-collector 0.3.5`.
